"""Deterministic standard-R4 output resource builders."""
from __future__ import annotations
from uuid import NAMESPACE_URL, uuid5

ORIGIN_SYSTEM = "https://oneaquahealth-hackathon.example/CodeSystem/data-origin"
DOMAIN_RESOURCE_TYPES = frozenset({"Device", "DetectedIssue", "Provenance", "CodeSystem", "Observation"})

def _tag(resource: dict) -> dict:
    """Mark a resource real-derived once; refuse to relabel a synthetic resource as real."""
    tags = resource.setdefault("meta", {}).setdefault("tag", [])
    if any(tag.get("code") == "synthetic" for tag in tags):
        raise ValueError("A synthetic resource must not be tagged real-derived.")
    marker = {"system": ORIGIN_SYSTEM, "code": "real-derived"}
    if marker not in tags:
        tags.append(marker)
    if resource.get("resourceType") in DOMAIN_RESOURCE_TYPES:
        resource.setdefault("text", {"status": "generated", "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by OneAquaHealth</div>"})
    return resource

def software_device(name: str, version: str) -> dict:
    return _tag({"resourceType": "Device", "id": str(uuid5(NAMESPACE_URL, f"{name}:{version}")), "deviceName": [{"name": name, "type": "user-friendly-name"}], "version": [{"value": version}]})

def detected_issue(finding, observation_ref: str, retrieval_date: str, rule_version: str) -> dict:
    stable = f"{observation_ref}:{finding.code}:{finding.path}:{rule_version}"
    return _tag({"resourceType": "DetectedIssue", "id": str(uuid5(NAMESPACE_URL, stable)), "status": "final", "code": {"text": finding.code}, "severity": "high" if finding.severity == "error" else "moderate", "implicated": [{"reference": observation_ref}], "detail": finding.message, "identifiedDateTime": retrieval_date})

def provenance(target_refs: list[str], device_ref: str, source_url: str, retrieval_date: str, rule_ids: list[str]) -> dict:
    stable = ":".join(target_refs + [device_ref, retrieval_date, *rule_ids])
    return _tag({"resourceType": "Provenance", "id": str(uuid5(NAMESPACE_URL, stable)), "recorded": retrieval_date, "target": [{"reference": ref} for ref in target_refs], "agent": [{"who": {"reference": device_ref}}], "entity": [{"role": "source", "what": {"reference": source_url, "display": "OneAquaHealth FHIR sandbox"}}], "reason": [{"text": ", ".join(rule_ids)}]})

def bundle(resources: list[dict]) -> dict:
    if any(not resource.get("id") for resource in resources):
        raise ValueError("Bundle resources must have deterministic ids.")
    stable = ":".join(resource["id"] for resource in resources)
    return _tag({"resourceType": "Bundle", "id": str(uuid5(NAMESPACE_URL, stable)), "type": "collection", "entry": [{"fullUrl": f"urn:uuid:{resource['id']}", "resource": resource} for resource in resources]})
