"""Derive the RUNTIME-only hash-pinned requirements from the full lockfile (container image build).

``requirements-lock.txt`` is compiled with the ``dev`` extra, so it also pins pytest, ruff, mypy and their
dependencies. The production image must not carry them. This script keeps exactly the packages that are
reachable from the runtime ``dependencies`` of ``pyproject.toml`` and copies their lockfile blocks unchanged
(versions and hashes), so the image installs a strict subset of the audited set with ``--require-hashes``.

The dependency edges are read from the ``# via`` comments pip-compile writes under every pin; a package
that lists ``oneaquahealth (pyproject.toml)`` as its only origin is a direct pin, and it is kept only when
it is named in the runtime ``dependencies`` list.

Usage (run by the Dockerfile, no network)::

    python runtime_requirements.py --lock requirements-lock.txt --pyproject pyproject.toml --output out.txt
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==")
_REQUIREMENT_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")
_SEPARATORS = re.compile(r"[-_.]+")
DEV_ONLY_NAMES = frozenset({"pytest", "pytest-cov", "hypothesis", "ruff", "mypy", "types-pyyaml", "coverage"})


def normalise(name: str) -> str:
    """PEP 503 normalised project name (``fhir.resources`` and ``fhir-resources`` are the same project)."""
    return _SEPARATORS.sub("-", name).lower()


def runtime_roots(pyproject_text: str) -> set[str]:
    """Normalised names of the runtime dependencies declared in ``[project].dependencies``."""
    data = tomllib.loads(pyproject_text)
    roots: set[str] = set()
    for requirement in data["project"]["dependencies"]:
        match = _REQUIREMENT_NAME.match(requirement)
        if match is None:
            raise ValueError(f"Cannot read a package name from {requirement!r}.")
        roots.add(normalise(match.group(1)))
    return roots


def parse_blocks(lock_text: str) -> tuple[list[str], dict[str, list[str]], dict[str, set[str]]]:
    """Return ``(header_lines, blocks, parents)``: the lockfile blocks by normalised name and each pin's ``via`` parents."""
    header: list[str] = []
    blocks: dict[str, list[str]] = {}
    parents: dict[str, set[str]] = {}
    current: str | None = None
    in_via = False
    for line in lock_text.splitlines():
        match = _PIN.match(line)
        if match:
            current = normalise(match.group(1))
            blocks[current] = [line]
            parents[current] = set()
            in_via = False
            continue
        if current is None:
            header.append(line)
            continue
        blocks[current].append(line)
        stripped = line.strip()
        if stripped.startswith("# via"):
            in_via = True
            inline = stripped[len("# via"):].strip()
            if inline:
                parents[current].add(inline)
        elif in_via and stripped.startswith("#"):
            parents[current].add(stripped.lstrip("#").strip())
        elif stripped and not stripped.startswith("--hash"):
            in_via = False
    return header, blocks, parents


def reachable(roots: set[str], parents: dict[str, set[str]]) -> set[str]:
    """Packages reachable from ``roots`` following requirement edges (parent -> child, from the ``via`` comments)."""
    children: dict[str, set[str]] = {}
    for child, owners in parents.items():
        for owner in owners:
            if " " in owner:  # "oneaquahealth (pyproject.toml)" or "-r file": not a package edge
                continue
            children.setdefault(normalise(owner), set()).add(child)
    seen: set[str] = set()
    pending = list(roots)
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        pending.extend(children.get(name, ()))
    return seen


def runtime_lock(lock_text: str, pyproject_text: str) -> str:
    """The runtime-only lockfile text; raises ``ValueError`` when a runtime dependency has no pin."""
    roots = runtime_roots(pyproject_text)
    header, blocks, parents = parse_blocks(lock_text)
    missing = sorted(roots - blocks.keys())
    if missing:
        raise ValueError(f"Runtime dependencies without a pin in the lockfile: {missing}")
    keep = reachable(roots, parents) & blocks.keys()
    leaked = sorted(keep & DEV_ONLY_NAMES)
    if leaked:
        raise ValueError(f"Development-only packages reachable from runtime dependencies: {leaked}")
    lines = [
        "# Runtime-only subset of requirements-lock.txt, generated by scripts/runtime_requirements.py.",
        "# Same versions and hashes as the full lockfile; development packages are not included.",
    ]
    for name in sorted(keep):
        lines.extend(blocks[name])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--lock", type=Path, required=True)
    parser.add_argument("--pyproject", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        text = runtime_lock(args.lock.read_text(encoding="utf-8"), args.pyproject.read_text(encoding="utf-8"))
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.output.name}: {sum(1 for line in text.splitlines() if _PIN.match(line))} pinned packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
